language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.2

install:
  - "travis_retry bundle install"

script: "bundle exec rake test"

gemfile:
  - gemfiles/rails_2.gemfile
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
